
package Enumerados;
public enum EnumeradoMenu {
    // solo son enumerados que serviran como constantes
    COMIDA,BEBIDA,ID_CONSUMO,ID_ALOJAMIENTO,NOMBRE_COMIDA,PRECIO_COMIDA,CANTIDAD,FECHA_CONSUMO,TOTAL,CLIENTE,NIT,
    REPORTE_INGRESOS_HOTEL,
    REPORTE_INGRESOS_DE_UN_CLIENTE,
    REPORTE_INGRESOS_HABITACION,
    REPORTE_HABITACION_MAS_POPULAR,
    HABITACION_OCUPADA,
    HABITACION_DISPONIBLE,
    REPORTE_CONSUMOS_RESTAURANTE,
    REPORTE_CLIENTES;
    
}
